### ISSUE TITLE
Domains and Certificates

### ISSUE THREAD

**Issue by qcaas-nhs-sjt** [lsc-sde/lsc-sde#3]
@vvcb We need to make a decision about how we want to handle Domains and Certificates.

I know that in the previous environment we were using what appeared to be a privately hosted domain name. This domain name is not reachable with the current DNS servers, so I'm guessing it was private, from what I've seen it also appears as though we were presenting everything on unencrypted connections via HTTP rather than HTTPS. This will not be viable on the new cluster due to the azure policies as per task #2 . As a result we will need to decide how we want to host this. 

We can easily create our own private DNS zone, or we can purchase a proper domain name and manage this via azure (or other services such as cloudflare). Likewise for SSL certificates we can buy a proper wildcard certificate (for the above domain) and utilise that, or we can use a self managed solution.

I generally advise the use of public certificates and DNS, this gives the maximum compatibility and massively reduces the overhead of managing the certificates, this will require a spend of course, but running our own certificate authority can actually be a lot higher than the cost of a wildcard certificate every year.

**Comment by vvcb** [comment]
The previous domain name for the TRE was internal by design as we never need it to be presented outside of the internal network - except through the AVD environment.  We need a new domain name. I will pick this up on email. 

In any case, all resources are secured with private endpoints anyway. For endpoints exposing a web service - eg. JupyterHub, OHDSI, Prefect UI, APIs, etc. - these should be accessible only on the private network or through a VDI solution that provides access to that network (which still has risks). Once again, for discussion at TDA to come up with a few options for how the end user outside of the internal network will access select services. @alex-maddocks FYI.

All traffic to nginx was https secured using a certificate generated by @PaulWoodhouseLTH but with TLS termination at this point. All traffic internal to the cluster was http.
