### ISSUE TITLE
Devcontainer with dind + k3s local K8s cluster provision 

### ISSUE THREAD

**Issue by m1p1h** [lsc-sde/lsc-sde#60]
@qcaas-nhs-sjt  @vvcb 

I've put together and pushed an initial lscsde devcontainer. It follows a docker-in-docker model to run a local cluster using K3s/k3d. The off-the-shelf minikube devcontainers arent suitable and microk8s wasnt an option due to installation constraints within containers. More details on what it currentl does are [here](https://docs.google.com/document/d/1Mz_clA6od8XsO9tcLK8EYqpmjHVBwFqvXH6a6Qr86dU/edit) which il move into our docs site shortly.

**Comment by vvcb** [comment]
@m1p1h , would you be able to link to the repo or commit for this please? This is hugely exciting and provides yet another way to develop and test in a consistent environment.

**Comment by m1p1h** [comment]
Yeah np - its in the root repo [here](https://github.com/lsc-sde/lsc-sde). Initial commit  https://github.com/lsc-sde/lsc-sde/commit/ab091ab10de8f2d53a3cf6ef0f82c0aa02845097

**Comment by qcaas-nhs-sjt** [comment]
@m1p1h @vvcb I would suggest that we all try to link any future commits to the issue that they are related to, this does make it easier to track individual changes, especially when working from the main branch.

You can do so by tagging the issue in your commit message, it's best to use the full path to the issue which is 
```
<org name>/<project name>#<issue number>
```

example:
```
lsc-sde/lsc-sde#24 simplified workflow
```

you can also just use the short code if your issue is on the same repository as you're committing to:
```
#24 simplified workflow
```

**Comment by m1p1h** [comment]
@vvcb @qcaas-nhs-sjt  , going to close this out. Would be great if you could test it on your own machines/codespaces. There's an extended guide on jekyll site > https://lsc-sde.github.io/lsc-sde/Secure-Data-Environment/Developers/Devcontainer-Guide.html
